spring.application.name=codebase-explainer
spring.datasource.url=jdbc:postgresql://localhost:5432/codebase_explainer
spring.datasource.username=postgres
spring.datasource.password=Manvi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.codec.max-in-memory-size=10MB
